import TextField from '@mui/material/TextField';
import DialogContent from '@mui/material/DialogContent';

export default function CustomerDialogContent({ customer, handleChange }) {
  return (
    <DialogContent>
      <TextField
        margin="dense"
        label="Brand"
        name="brand"
        value={customer.brand}
        onChange={handleChange}
        fullWidth
        variant="standard"
      />
      <TextField
        margin="dense"
        label="Model"
        name="model"
        value={customer.model}
        onChange={handleChange}
        fullWidth
        variant="standard"
      />
      <TextField
        margin="dense"
        label="Color"
        name="color"
        value={customer.color}
        onChange={handleChange}
        fullWidth
        variant="standard"
      />
      <TextField
        margin="dense"
        label="Fuel"
        name="fuel"
        value={customer.fuel}
        onChange={handleChange}
        fullWidth
        variant="standard"
      />
      <TextField
        margin="dense"
        label="Year"
        name="year"
        value={customer.year}
        onChange={handleChange}
        fullWidth
        variant="standard"
      />
      <TextField
        margin="dense"
        label="Price"
        name="price"
        value={customer.price}
        onChange={handleChange}
        fullWidth
        variant="standard"
      />
    </DialogContent>
  );
}