import TextField from '@mui/material/TextField';
import DialogContent from '@mui/material/DialogContent';

export default function CustomerDialogContent({ customer, handleChange }) {
  return (
    <DialogContent>
      <TextField
        margin="dense"
        label="Firstname"
        name="firstname"
        value={customer.firstname}
        onChange={handleChange}
        fullWidth
        variant="standard"
      />
      <TextField
        margin="dense"
        label="Lastname"
        name="lastname"
        value={customer.lastname}
        onChange={handleChange}
        fullWidth
        variant="standard"
      />
      <TextField
        margin="dense"
        label="streetaddress"
        name="streetaddress"
        value={customer.streetaddress}
        onChange={handleChange}
        fullWidth
        variant="standard"
      />
      <TextField
        margin="dense"
        label="Postcode"
        name="postcode"
        value={customer.postcode}
        onChange={handleChange}
        fullWidth
        variant="standard"
      />
      <TextField
        margin="dense"
        label="City"
        name="city"
        value={customer.city}
        onChange={handleChange}
        fullWidth
        variant="standard"
      />
      <TextField
        margin="dense"
        label="Email"
        name="email"
        value={customer.email}
        onChange={handleChange}
        fullWidth
        variant="standard"
      />
        <TextField
        margin="dense"
        label="Phone"
        name="phone"
        value={customer.phone}
        onChange={handleChange}
        fullWidth
        variant="standard"
      />
    </DialogContent>
  );
}